version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "12:00"
      timezone: "America/New_York"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
