#!/bin/sh

# Define the GitHub repository
REPO="iton0/hkup-cli"

# Determine the binary name and installation path based on the OS
case "$(uname)" in
  Linux)
    BINARY_NAME="hkup-linux"
    INSTALL_PATH="/usr/local/bin/hkup"
    ;;
  Darwin)
    BINARY_NAME="hkup-darwin"
    INSTALL_PATH="/usr/local/bin/hkup"
    ;;
  # CYGWIN*|MINGW32*|MSYS*|MINGW*)
  #   BINARY_NAME="hkup.exe"
  #   INSTALL_PATH="$USERPROFILE/bin/hkup.exe"  # Use a user-specific directory
  #   mkdir -p "$USERPROFILE/bin"  # Create the bin directory if it doesn't exist
  #   ;;
  *)
    echo "Unsupported OS: $(uname)"
    exit 1
    ;;
esac

# Get the latest release version from GitHub
LATEST_RELEASE=$(curl -s "https://api.github.com/repos/$REPO/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
echo "Latest version: $LATEST_RELEASE"

# Download the binary for the latest release to a temporary location
TEMP_PATH=$(mktemp)
echo "Downloading $BINARY_NAME version $LATEST_RELEASE..."
curl -L "https://github.com/$REPO/releases/download/$LATEST_RELEASE/$BINARY_NAME" -o "$TEMP_PATH"

# Move the downloaded binary to the installation path
sudo mv "$TEMP_PATH" "$INSTALL_PATH"

# Make it executable (Linux and macOS)
if [ "$(uname)" != "CYGWIN" ] && [ "$(uname)" != "MINGW" ]; then
  sudo chmod +x "$INSTALL_PATH"  # Use sudo to change permissions
fi

echo "hkup installed successfully!"

